#!/bin/bash

export NTW_NODE_DIST_URL=https://artifacts.netflix.net/nodejs-dist
if [ "$CI" != "" ]; then
  export NTW_HOME=/agent/ntw-cache/$EXECUTOR_NUMBER
  export YARN_CACHE_FOLDER=/agent/yarn-cache/$EXECUTOR_NUMBER
fi

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
export SCRIPT_DIR

. $SCRIPT_DIR/.ntw.sh

selectNode v16.13.1
selectTool yarn 1.22.17

exec yarn "$@"
